build openVPN client profile
opendevstack/ods-core pull request #930
Opened 2020-12-17 08:53 UTC by s2oBCN

Script to generate an OpenVPN client profile (at least needed in Windows)

2020-12-17 16:02 UTC, stitakis commented
@michaelsauter do we have a formatting standard or/and standard way to build bash scripts? Asking because we have many of them... maybe is time to think about to introduce some conventions for bash scripts.

2020-12-17 20:49 UTC, metmajer commented
Thanks, @s2oBCN. Can you please provide some context on how users will benefit from it? You mention Windows, but the paths in the script refer to Unix paths. Some inline documentation on the usage would also help.

2020-12-18 07:31 UTC, michaelsauter commented
@stitakis Yes please run them through https://github.com/koalaman/shellcheck. Most more recently added scripts adhere to spellcheck's rules, and are also checked in GitHub Actions, see https://github.com/opendevstack/ods-core/blob/master/.github/workflows/continuous-integration-workflow.yml#L81.

2021-01-14 12:49 UTC, metmajer requested changes
Hi @s2oBCN, a few minor improvements would help. Cheers!

2021-01-14 12:49 UTC, metmajer commented on ods-devenv/openvpn/build-client-profile.sh
> +# Run this script in the EDP server
Can you rename "in the EDP server" to "in your EDP / ODS box"?

2021-01-14 12:49 UTC, metmajer commented on ods-devenv/openvpn/build-client-profile.sh
> +# Arguments:
Can you provide an "Example:" block with an example script call underneath the "Arguments:" block?

2021-01-14 12:49 UTC, metmajer commented on ods-devenv/openvpn/build-client-profile.sh
> +    echo "params: <server address> <client>"
<client> -> <client-cert-name>?

2021-01-26 19:12 UTC, metmajer commented
@s2oBCN let's finalise and close down the issue please

2021-02-01 15:27 UTC, stitakis commented
@s2oBCN it looks good to me... one check is failing... can you please update the CHANGELOG.md? Just add this feature to the section `## Unreleased`

2021-02-03 14:03 UTC, stitakis approved these changes
looks good to me!

2021-02-04 08:14 UTC, metmajer approved these changes
Like it, @s2oBCN. This comes very handy :) Thanks!

2021-02-04 08:55 UTC, merged