Install Aquasec scannercli on jenkins base image
opendevstack/ods-core pull request #976
Opened 2021-04-22 11:05 UTC by segator

Aquasec is installed on base image if ```JENKINS_AGENT_BASE_AQUASEC_SCANNERCLI_URL``` it's defined on ods-configuration

Example URL
```
#JENKINS_AGENT_BASE_AQUA_SCANNERCLI_URL=https://<USER>:<PASSWORD>@download.aquasec.com/scanner/6.0.0/scannercli
```

2021-04-22 11:57 UTC, michaelsauter requested changes
You'll need to cherry-pick your changes on top of master, 3.x based branches cannot be merged into master ...

2021-04-30 17:18 UTC, segator commented
> You'll need to cherry-pick your changes on top of master, 3.x based branches cannot be merged into master ...
Sorry for the delay on fixing this, Done!

2021-04-30 17:26 UTC, clemensutschig approved these changes

2021-05-03 07:16 UTC, michaelsauter approved these changes

2021-05-03 10:58 UTC, merged