Make sure result image is public
opendevstack/ods-core pull request #990
Opened 2021-06-14 21:41 UTC by serverhorror

This _should_ make sure the resulting image will be publicly available.

It is quite hard to test as there is no VMWare available and it will not build without the base OVA being made available as well.

Changing that might take a while as there are a bunch of assumptions in these scripts.

I'd prefer if this was based on the official CentOS images rather than a kickstarted OVA:

```diff
diff --git a/ods-devenv/packer/CentOS2ODSBox.json b/ods-devenv/packer/CentOS2ODSBox.json
index 495d849..ba517c5 100644
--- a/ods-devenv/packer/CentOS2ODSBox.json
+++ b/ods-devenv/packer/CentOS2ODSBox.json
@@ -12,9 +12,11 @@
             "region": "eu-west-1",
             "source_ami_filter": {
                 "filters": {
-                    "image-id": "{{user `ami_id`}}"
+                    "name": "CentOS 7*",
+                    "architecture": "x86_64"
                 },
-                "owners": "275438041116"
+                "owners": "125523088429",
+                "most_recent": true
             },
             "instance_type": "{{user `instance_type`}}",
             "ssh_username": "{{user `username`}}",
```

#988

2021-06-15 05:31 UTC, clemensutschig submitted a review, later dismissed

2021-06-15 05:37 UTC, clemensutschig commented
@serverhorror can you rebase to ods-devenv? Then we can try it there..  if not i do it.

2021-06-15 05:49 UTC, metmajer commented
@serverhorror let's try this out first with @stitakis @s2oBCN. Would like to see the use of template variables again. We could put the arguments you hard-wired into the script into a table in the README.md for reference.

2021-06-15 07:12 UTC, clemensutschig commented
@stitakis  - I would merge this into ods-devenv .. (and give this an update .. to latest master as well) :;D

2021-06-15 12:10 UTC, serverhorror commented
@clemensutschig Yes, done.

@metmajer I'm a little confused by the organization of `ods-devenv/scripts` and ods-devenv/packer` to be honest. I just had a quick glance but it seems quite complex to create VMWare and based on that EC2. There are a lot of expectations (e.g. an `openshift` user that exists) that the ebs-builder has. I think I'm misunderstanding the idea.

If someone explains why the VMWare stuff is used as a base and running different scripts than the EC2 stuff I'm more than happy. Right now I'm a bit confused and don't feel comfortable enough making these changes.

Putting this on top of the official CentOS images seems like a good idea to make it publicly availabe, right now it's a bit hard to do so if (like me) one doesn't have access to any VMWare infrastructure.

2021-06-15 12:13 UTC, clemensutschig commented
@serverhorror  we had some issues with the public one - that's why we create one on vmware and push it up...

2021-06-15 14:02 UTC, serverhorror commented
> we had some issues with the public one

Ah interesting. Of course that's a good reason then ...

2021-07-07 20:02 UTC, metmajer commented
@serverhorror @clemensutschig can we move on with this one?

2021-07-10 09:41 UTC, clemensutschig commented
@stitakis I updated ods-devenv with latest master now .. to see if the base CI works again .. (and we get a built image) - once done, I 'll merge this .. though ... the error above (actions, sq) is slightly worrysome?! @gerardcl  andy ideas

2021-07-11 06:33 UTC, clemensutschig approved these changes

2021-07-12 20:13 UTC, metmajer commented
@michaelsauter @jorge-romero the recent SonarQube errors have been fixed. Can you advise @serverhorror on how to fix his tests?

2021-11-09 11:08 UTC, stitakis requested changes

2021-11-09 11:08 UTC, stitakis commented on ods-devenv/packer/CentOS2ODSBox.json
> +            "ami_groups": [
This change was tried in master and broke the build. 

Let us hold on on this until we have a working implementation branch `feature/ods-devenv`

2021-11-09 11:09 UTC, stitakis commented
I'll convert it to draft PR for further discussion and development

2021-11-09 11:10 UTC, stitakis commented
see related build error issue #1062

2022-02-08 08:57 UTC, stitakis commented
Closing this as it seems to be not needed

2022-02-08 08:57 UTC, closed without merging